services:
  - type: web
    name: embykeeper
    runtime: docker
    plan: free
    branch: stable
    dockerfilePath: ./deploy/Dockerfile
    dockerContext: ./deploy/
    healthCheckPath: /healthz
    envVars:
      - key: EK_WEBPASS
        sync: false
    autoDeploy: true
