name: Close Stale Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: '该 Issue 长时间无活动将在 5 天后关闭, 回复或移除 `stale` 标签以延迟关闭.'
          close-issue-message: '该 Issue 因长时间无活动而关闭, 若您有疑问请继续评论.'
          days-before-stale: 30
          days-before-close: 5
